markdown: rdiscount
permalink: /:title
highlighter: pygments

title: "@wizcabbit"

url: http://localhost:9007
is_debug: true

author:
  name: wizcabbit
  email: frontfreewzy@gmail.com

author_info: <a href="http://blog.cabbit.me/">wizcabbit</a>

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "leetcode"
      type: "posts"
    values:
      categories: "leetcode"

exclude: ["node_modules",  "package.json", "Gruntfile.js", ".gitignore", "README.md"]
